'use client';

import { useState } from 'react';
import type { District } from '@/lib/data';
import allocationData from '@/data/allocation.json';
import { fmtInt, fmtMoney, fmtMoneyFull } from '@/lib/format';

type Allocation = (typeof allocationData.districts)[keyof typeof allocationData.districts];
const ALLOCATION = allocationData.districts as Record<string, Allocation>;

/**
 * What the state allocation actually buys, in the order it is generated: the
 * prototypical model produces staff (salaries, then the benefits that come
 * with them), adds the non-staff operating money every school needs, and then
 * layers the categorical programs on top.
 *
 * These are real allotments from OSPI's apportionment extract, not a model -
 * see scripts/build-state-allocation.py.
 */
const PARTS: {
  key: keyof Allocation;
  label: string;
  color: string;
  blurb: string;
}[] = [
  {
    key: 'salaries',
    label: 'Salaries',
    color: '#1d4ed8',
    blurb: 'Teachers, principals, and classified staff generated by the model',
  },
  {
    key: 'benefits',
    label: 'Benefits',
    color: '#2a78d6',
    blurb: 'Health coverage (SEBB), retirement, and payroll taxes for those staff',
  },
  {
    key: 'msoc',
    label: 'Materials & operating costs',
    color: '#7ea9e8',
    blurb: 'Curriculum, technology, utilities, insurance, and facilities upkeep',
  },
  {
    key: 'otherBasicEducation',
    label: 'Other basic education',
    color: '#b9d0f2',
    blurb:
      'Career and technical education, skill centers, Running Start, Alternative Learning Experience, and substitutes - net of local revenues the state deducts',
  },
  {
    key: 'specialEd',
    label: 'Special education',
    color: '#d15f78',
    blurb: 'The excess-cost allocation on top of basic education',
  },
  {
    key: 'transportation',
    label: 'Transportation',
    color: '#9a6a39',
    blurb: 'Buses, drivers, and fuel, funded by its own formula',
  },
  {
    key: 'bilingual',
    label: 'Multilingual learners',
    color: '#009978',
    blurb: 'Transitional Bilingual Instruction Program',
  },
  {
    key: 'learningAssistance',
    label: 'Learning assistance',
    color: '#bd7600',
    blurb: 'LAP: extra academic support where students are behind',
  },
  {
    key: 'highlyCapable',
    label: 'Highly capable',
    color: '#7257c7',
    blurb: 'Programs for highly capable students',
  },
  {
    key: 'levyEqualization',
    label: 'Levy equalization',
    color: '#8b5cf6',
    blurb: 'Local Effort Assistance for property-poor districts',
  },
  {
    key: 'food',
    label: 'School food',
    color: '#0e9f6e',
    blurb: 'State support for school meals',
  },
  {
    key: 'otherState',
    label: 'Other state programs',
    color: '#94a3b8',
    blurb: 'Smaller categorical grants and one-time allocations',
  },
];

function StepIcon({ index }: { index: number }) {
  const common = {
    viewBox: '0 0 24 24',
    className: 'h-8 w-8',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: 1.8,
    strokeLinecap: 'round' as const,
    strokeLinejoin: 'round' as const,
    'aria-hidden': true,
  };
  if (index === 0)
    return (
      <svg {...common}>
        <circle cx="12" cy="12" r="9" />
        <path d="M12 7v5l3 2" />
      </svg>
    );
  if (index === 1)
    return (
      <svg {...common}>
        <path d="m3 10 9-6 9 6M5 9v10h14V9M9 19v-5h6v5M8 11h.01M16 11h.01" />
      </svg>
    );
  if (index === 2)
    return (
      <svg {...common}>
        <circle cx="8" cy="8" r="3" />
        <circle cx="17" cy="8.5" r="2.5" />
        <path d="M2.5 19c.5-3.5 2.4-5.5 5.5-5.5s5 2 5.5 5.5M14 14c3.8-.8 6.6 1 7.2 5" />
      </svg>
    );
  if (index === 3)
    return (
      <svg {...common}>
        <circle cx="12" cy="12" r="9" />
        <path d="M15 8.5c-.7-.6-1.6-.9-2.7-.9-1.6 0-2.8.8-2.8 2s1 1.8 3 2.3 3 1.2 3 2.4-1.3 2.1-3.1 2.1c-1.2 0-2.3-.4-3.1-1.1M12 5.5v13" />
      </svg>
    );
  if (index === 4)
    return (
      <svg {...common}>
        <path d="M4 6.5A2.5 2.5 0 0 1 6.5 4H20v14H6.5A2.5 2.5 0 0 0 4 20.5z" />
        <path d="M4 6.5v14M8 8h8M8 12h6" />
      </svg>
    );
  if (index === 5)
    return (
      <svg {...common}>
        <path d="M12 20s-7-4.3-7-10a4 4 0 0 1 7-2.6A4 4 0 0 1 19 10c0 5.7-7 10-7 10z" />
      </svg>
    );
  return (
    <svg {...common}>
      <path d="M4 7.5h16v11H4zM6 7.5V5h12v2.5M4 11h16M16.5 15h.01" />
    </svg>
  );
}

/** A little cluster of people icons - a wordless "staff" visual. */
function PeopleCluster() {
  return (
    <span className="inline-flex gap-0.5" aria-hidden>
      {Array.from({ length: 5 }, (_, i) => (
        <svg key={i} viewBox="0 0 24 24" className="h-5 w-5" fill="#2a78d6">
          <circle cx="12" cy="7" r="4" />
          <path d="M4 21c0-4.4 3.6-8 8-8s8 3.6 8 8z" />
        </svg>
      ))}
    </span>
  );
}

/** Big number + tiny caption - the scannable payoff for each step. */
function Stat({ big, cap }: { big: string; cap: string }) {
  return (
    <div>
      <div className="text-3xl md:text-4xl font-bold text-accent-deep tabular-nums leading-none">
        {big}
      </div>
      <div className="mt-1 text-xs text-ink-muted">{cap}</div>
    </div>
  );
}

type Step = {
  headline: string;
  blurb: string;
  visual: (district: District, allocation: Allocation | null) => React.ReactNode;
};

const STEPS: Step[] = [
  {
    headline: 'Count students by time',
    blurb: 'Part-time counts as part of one.',
    visual: (d) => (
      <Stat
        big={fmtInt(Math.round(d.fundingEnrollment))}
        cap={`funding FTE (not ${fmtInt(d.enrollment)} kids)`}
      />
    ),
  },
  {
    headline: 'Make model schools',
    blurb: 'Same yardstick everywhere.',
    visual: (d) => {
      const models =
        d.fundingFte.elementary / 400 + d.fundingFte.middle / 432 + d.fundingFte.high / 600;
      return <Stat big={models.toFixed(0)} cap="pretend model schools" />;
    },
  },
  {
    headline: 'Add staff to each',
    blurb: 'Teachers, nurses, admin, custodians.',
    visual: () => (
      <div>
        <PeopleCluster />
        <div className="mt-1 text-xs text-ink-muted">a staff recipe per school</div>
      </div>
    ),
  },
  {
    headline: 'Turn staff into money',
    blurb: 'Positions × salaries, plus benefits.',
    visual: (d, a) =>
      a ? (
        <Stat
          big={fmtMoney(a.salaries + a.benefits)}
          cap="salaries + benefits"
        />
      ) : (
        <Stat big={fmtMoney(d.rev.state)} cap="state allocation" />
      ),
  },
  {
    headline: 'Add operating money',
    blurb: 'Books, power, internet, insurance.',
    visual: (d, a) =>
      a ? (
        <Stat big={fmtMoney(a.msoc)} cap="materials & operating costs" />
      ) : (
        <Stat big="$1,600+" cap="per student for supplies" />
      ),
  },
  {
    headline: 'Extra for extra needs',
    blurb: 'Some students bring more.',
    visual: (d, a) => {
      if (a) {
        const needs = a.specialEd + a.bilingual + a.learningAssistance + a.highlyCapable;
        return <Stat big={fmtMoney(needs)} cap="special ed, multilingual, LAP, highly capable" />;
      }
      const pct = (n: number) => Math.round((n / d.enrollment) * 100);
      const chips = [
        [`${pct(d.demo.sped)}%`, 'special ed'],
        [`${pct(d.demo.ell)}%`, 'multilingual'],
        [`${pct(d.demo.lowIncome)}%`, 'low-income'],
      ];
      return (
        <div className="flex flex-wrap gap-2">
          {chips.map(([n, label]) => (
            <span key={label} className="rounded-lg bg-accent-soft px-2.5 py-1 text-center">
              <span className="block text-lg font-bold text-accent-deep tabular-nums leading-none">
                {n}
              </span>
              <span className="block text-[10px] text-ink-muted">{label}</span>
            </span>
          ))}
        </div>
      );
    },
  },
  {
    headline: 'Add it all up',
    blurb: 'The total the state sends.',
    visual: (d, a) => (
      <Stat
        big={fmtMoney(a ? a.total : d.rev.state)}
        cap="total state allocation"
      />
    ),
  },
];

/**
 * The stacked composition of the state allocation. This is the point of the
 * whole walkthrough: salaries are the largest single piece but nowhere near
 * all of it, so reading the state total as "the staff budget" is wrong.
 */
function AllocationBar({
  allocation,
  district,
}: {
  allocation: Allocation;
  district: District;
}) {
  const [hover, setHover] = useState<string | null>(null);
  const total = allocation.total;
  // A negative "other basic education" residual shows up for a handful of
  // districts whose deductible local revenues exceed their CTE and Running
  // Start money. It is always under 3% and cannot be drawn as a width, so the
  // bar clamps it while the table below still reports the real figure.
  const parts = PARTS.map((p) => ({ ...p, value: allocation[p.key] as number })).filter(
    (p) => p.value !== 0
  );
  const drawable = parts.filter((p) => p.value > 0);
  const drawTotal = drawable.reduce((s, p) => s + p.value, 0) || 1;
  const active = parts.find((p) => p.key === hover);

  return (
    <div className="mt-5 rounded-xl border border-line bg-surface p-4 md:p-5">
      <div className="flex items-baseline justify-between gap-3 flex-wrap">
        <h3 className="font-bold">
          What the {fmtMoney(total)} state allocation pays for
        </h3>
        <p className="text-xs text-ink-muted">
          {fmtMoneyFull(Math.round(total / district.fundingEnrollment))} per funding FTE
        </p>
      </div>
      <p className="mt-1 text-sm text-ink-secondary">
        Salaries are{' '}
        <strong className="text-ink">
          {Math.round((100 * allocation.salaries) / total)}%
        </strong>{' '}
        of it. The rest is benefits, operating costs, and the programs layered on
        top.
      </p>

      <div
        className="mt-4 flex h-8 rounded overflow-hidden bg-paper"
        style={{ gap: 2 }}
        role="img"
        aria-label={`State allocation composition: ${parts
          .map((p) => `${p.label} ${fmtMoney(p.value)}`)
          .join(', ')}`}
      >
        {drawable.map((p) => (
          <div
            key={p.key}
            className="relative flex items-center justify-center transition-opacity"
            style={{
              width: `${(100 * p.value) / drawTotal}%`,
              background: p.color,
              opacity: hover && hover !== p.key ? 0.4 : 1,
            }}
            onMouseEnter={() => setHover(p.key)}
            onMouseLeave={() => setHover(null)}
          >
            {(100 * p.value) / drawTotal >= 9 && (
              <span className="text-xs font-semibold text-white select-none">
                {Math.round((100 * p.value) / drawTotal)}%
              </span>
            )}
          </div>
        ))}
      </div>

      <p className="mt-2 min-h-[1.5rem] text-xs text-ink-muted">
        {active ? active.blurb : 'Hover a band to see what it covers.'}
      </p>

      <table className="mt-2 w-full text-sm">
        <caption className="sr-only">
          State allocation by component, {allocationData.schoolYear}
        </caption>
        <tbody>
          {parts.map((p) => (
            <tr
              key={p.key}
              className="border-t border-line"
              onMouseEnter={() => setHover(p.key)}
              onMouseLeave={() => setHover(null)}
            >
              <td className="py-1.5 pr-2">
                <span
                  className="mr-2 inline-block h-2.5 w-2.5 rounded-sm align-middle"
                  style={{ background: p.color }}
                  aria-hidden
                />
                <span className="text-ink-secondary">{p.label}</span>
              </td>
              <td className="py-1.5 text-right tabular-nums">
                {fmtMoneyFull(p.value)}
              </td>
              <td className="w-14 py-1.5 text-right tabular-nums text-ink-muted">
                {Math.round((100 * p.value) / total)}%
              </td>
            </tr>
          ))}
          <tr className="border-t-2 border-line font-bold">
            <td className="py-2">Total state allocation</td>
            <td className="py-2 text-right tabular-nums">{fmtMoneyFull(total)}</td>
            <td className="py-2 text-right tabular-nums">100%</td>
          </tr>
        </tbody>
      </table>

      <p className="mt-3 text-xs text-ink-muted">
        OSPI Apportionment Final Extract, {allocationData.schoolYear} - the data
        behind the 1191 Apportionment Summary. State general-fund allotments
        only, so it differs slightly from the{' '}
        {fmtMoney(district.rev.state)} of state revenue the district reported on
        its F-196 for the same year.
      </p>
    </div>
  );
}

export default function FundingJourney({ district }: { district: District }) {
  const allocation = ALLOCATION[district.code] ?? null;

  return (
    <div className="mt-6">
      <ol aria-label="Seven steps in school funding">
        {STEPS.map((item, index) => {
          const isLast = index === STEPS.length - 1;
          return (
            <li key={item.headline} className="relative flex gap-4 md:gap-5">
              {/* Rail: big numbered icon + connecting line */}
              <div className="flex flex-col items-center">
                <span className="relative flex h-16 w-16 shrink-0 items-center justify-center rounded-full bg-accent text-white">
                  <StepIcon index={index} />
                  <span className="absolute -top-1 -left-1 flex h-6 w-6 items-center justify-center rounded-full bg-accent-deep text-xs font-bold text-white ring-2 ring-surface">
                    {index + 1}
                  </span>
                </span>
                {!isLast && <span className="w-0.5 flex-1 bg-accent-soft my-1" aria-hidden />}
              </div>

              {/* Content: short headline + big visual */}
              <div className={`min-w-0 flex-1 ${isLast ? 'pb-1' : 'pb-6'}`}>
                <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between rounded-xl border border-line bg-surface p-4">
                  <div className="min-w-0">
                    <h3 className="text-lg md:text-xl font-bold leading-tight">
                      {item.headline}
                    </h3>
                    <p className="mt-0.5 text-sm text-ink-secondary">{item.blurb}</p>
                  </div>
                  <div className="shrink-0 sm:text-right sm:pl-4">
                    {item.visual(district, allocation)}
                  </div>
                </div>
              </div>
            </li>
          );
        })}
      </ol>

      {allocation && <AllocationBar allocation={allocation} district={district} />}
    </div>
  );
}
