'use client';

import { useState } from 'react';

type SchoolType = 'elementary' | 'middle' | 'high';

/**
 * Staffing generated by the prototypical school formula (base values,
 * RCW 28A.150.260), expressed per student so any school size works.
 */
const MODELS: Record<
  SchoolType,
  {
    label: string;
    grades: string;
    proto: number;
    teachersPerStudent: number;
    perStudent: Record<string, number>;
  }
> = {
  elementary: {
    label: 'Elementary',
    grades: 'K–6 · state prototype: 400 students',
    proto: 400,
    // K-3 at 17:1 (≈4/7 of students), grades 4-6 at 27:1 (≈3/7)
    teachersPerStudent: (4 / 7) / 17 + (3 / 7) / 27,
    perStudent: {
      Principals: 1.253 / 400,
      Counselors: 0.493 / 400,
      'Teacher-librarians': 0.663 / 400,
      'Office staff': 2.012 / 400,
      Custodians: 1.657 / 400,
      Nurses: 0.076 / 400,
    },
  },
  middle: {
    label: 'Middle',
    grades: '7–8 · state prototype: 432 students',
    proto: 432,
    teachersPerStudent: 1 / 28.53,
    perStudent: {
      Principals: 1.353 / 432,
      Counselors: 1.216 / 432,
      'Teacher-librarians': 0.519 / 432,
      'Office staff': 2.325 / 432,
      Custodians: 1.942 / 432,
      Nurses: 0.06 / 432,
    },
  },
  high: {
    label: 'High school',
    grades: '9–12 · state prototype: 600 students',
    proto: 600,
    teachersPerStudent: 1 / 28.74,
    perStudent: {
      Principals: 1.88 / 600,
      Counselors: 2.539 / 600,
      'Teacher-librarians': 0.523 / 600,
      'Office staff': 3.269 / 600,
      Custodians: 2.965 / 600,
      Nurses: 0.096 / 600,
    },
  },
};

function Person({ ghost = false }: { ghost?: boolean }) {
  return (
    <svg
      viewBox="0 0 24 24"
      className="w-[15px] h-[15px]"
      fill={ghost ? '#c3c2b7' : '#2a78d6'}
      opacity={ghost ? 0.35 : 1}
      aria-hidden
    >
      <circle cx="12" cy="6.5" r="4.5" />
      <path d="M3.5 22c0-4.7 3.8-8.5 8.5-8.5s8.5 3.8 8.5 8.5z" />
    </svg>
  );
}

function StaffIcons({ count }: { count: number }) {
  const whole = Math.floor(count);
  const frac = count - whole;
  const shown = Math.min(whole, 60);
  return (
    <span className="inline-flex flex-wrap items-end gap-[3px] align-middle">
      {Array.from({ length: shown }, (_, i) => (
        <span key={i} className="dot-in" style={{ animationDelay: `${Math.min(i, 30) * 14}ms` }}>
          <Person />
        </span>
      ))}
      {whole > shown && (
        <span className="text-xs text-ink-muted mx-1">+{whole - shown} more</span>
      )}
      {frac > 0.005 && (
        <span
          className="relative inline-block dot-in"
          style={{ animationDelay: `${Math.min(shown, 31) * 14}ms` }}
          title={`${Math.round(frac * 100)}% of one position`}
        >
          <Person ghost />
          <span
            className="absolute inset-0 overflow-hidden"
            style={{ width: `${Math.max(frac * 100, 8)}%` }}
          >
            <Person />
          </span>
        </span>
      )}
    </span>
  );
}

function fmtFte(n: number) {
  return n >= 10 ? String(Math.round(n)) : n >= 1 ? n.toFixed(1) : n.toFixed(2);
}

export default function SchoolBuilder() {
  const [type, setType] = useState<SchoolType>('elementary');
  const [students, setStudents] = useState(400);
  const m = MODELS[type];

  const teachers = students * m.teachersPerStudent;
  const staff = Object.entries(m.perStudent).map(([role, rate]) => ({
    role,
    fte: students * rate,
  }));
  const nurses = staff.find((s) => s.role === 'Nurses')!.fte;
  const counselors = staff.find((s) => s.role === 'Counselors')!.fte;
  const totalStaff = teachers + staff.reduce((sum, s) => sum + s.fte, 0);
  const nurseHours = nurses * 40;
  const isProto = students === m.proto;

  return (
    <div className="card p-5 md:p-7">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 className="text-xl md:text-2xl font-bold">
            Run the formula yourself
          </h3>
          <p className="mt-1 text-sm text-ink-secondary">
            This is the real math from RCW 28A.150.260. Pick a school, drag the
            slider, watch who appears.
          </p>
        </div>
        <div className="flex rounded-lg border border-line overflow-hidden">
          {(Object.keys(MODELS) as SchoolType[]).map((t) => (
            <button
              key={t}
              onClick={() => {
                setType(t);
                setStudents(MODELS[t].proto);
              }}
              className={`px-3.5 py-2 text-sm font-medium transition-colors ${
                type === t
                  ? 'bg-accent text-white'
                  : 'bg-surface text-ink-secondary hover:bg-accent-wash'
              }`}
            >
              {MODELS[t].label}
            </button>
          ))}
        </div>
      </div>

      <div className="mt-5">
        <div className="flex items-baseline justify-between flex-wrap gap-2">
          <label htmlFor="sb-students" className="text-sm text-ink-secondary">
            Students in your {m.label.toLowerCase()} school
          </label>
          <span className="text-2xl font-bold tabular-nums">
            {students}
            {isProto && (
              <span className="ml-2 text-xs font-semibold text-accent align-middle">
                ★ the state&apos;s prototype
              </span>
            )}
          </span>
        </div>
        <input
          id="sb-students"
          type="range"
          min={50}
          max={1500}
          step={10}
          value={students}
          onChange={(e) => setStudents(Number(e.target.value))}
          className="mt-1 w-full"
          style={{ accentColor: '#256abf' }}
        />
        <div className="flex justify-between text-xs text-ink-muted">
          <span>50</span>
          <span className="text-ink-muted">{m.grades}</span>
          <span>1,500</span>
        </div>
      </div>

      <div className="mt-6 space-y-4">
        <div>
          <div className="flex items-baseline gap-2 flex-wrap">
            <span className="w-40 shrink-0 text-sm font-semibold">Teachers</span>
            <span className="text-sm tabular-nums font-bold text-accent-deep w-12">
              {fmtFte(teachers)}
            </span>
            <span className="text-xs text-ink-muted">
              ≈ {Math.round(students / teachers)} students per funded teacher
            </span>
          </div>
          <div className="mt-1.5 pl-0 md:pl-40">
            <StaffIcons count={teachers} />
          </div>
        </div>

        {staff.map(({ role, fte }) => (
          <div key={role}>
            <div className="flex items-baseline gap-2 flex-wrap">
              <span className="w-40 shrink-0 text-sm font-semibold">{role}</span>
              <span className="text-sm tabular-nums font-bold text-accent-deep w-12">
                {fmtFte(fte)}
              </span>
              {role === 'Counselors' && (
                <span className="text-xs text-ink-muted">
                  1 for every {Math.round(students / counselors).toLocaleString()}{' '}
                  students · experts recommend 1 per 250
                </span>
              )}
              {role === 'Nurses' && (
                <span className="text-xs text-ink-muted">
                  ≈ {nurseHours < 10 ? nurseHours.toFixed(1) : Math.round(nurseHours)}{' '}
                  hours of nurse time per week — for the whole school
                </span>
              )}
            </div>
            <div className="mt-1.5 pl-0 md:pl-40">
              <StaffIcons count={fte} />
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 border-t border-line pt-4 flex flex-wrap items-baseline justify-between gap-2">
        <p className="text-sm text-ink-secondary">
          <strong className="text-ink">{fmtFte(totalStaff)} state-funded adults</strong>{' '}
          for {students.toLocaleString()} students
        </p>
        <p className="text-xs text-ink-muted">
          Base formula values; faded figures are fractions of one full-time job.
          Districts use levies to hire beyond this.
        </p>
      </div>
    </div>
  );
}
